steps:
- task: UseDotNet@2
  displayName: install dotnet core sdk 2.1
  inputs:
    packageType: sdk
    version: 2.1.x

- task: UseDotNet@2
  displayName: install dotnet core sdk 3.0
  inputs:
    packageType: sdk
    version: 3.0.x

- task: UseDotNet@2
  displayName: install dotnet core sdk 3.1
  inputs:
    packageType: sdk
    version: 3.1.x

- task: UseDotNet@2
  displayName: install dotnet core sdk 5
  inputs:
    packageType: sdk
    version: $(dotnetCoreSdk5Version)
    includePreviewVersions: true