version: '3'
services:
  IntegrationTests:
    network_mode: "host"
    environment:
      - MONGO_HOST=localhost
      - SERVICESTACK_REDIS_HOST=127.0.0.1:6379
      - STACKEXCHANGE_REDIS_HOST=127.0.0.1:6379
      - ELASTICSEARCH6_HOST=127.0.0.1:9200
      - ELASTICSEARCH5_HOST=127.0.0.1:9200
      - SQLSERVER_CONNECTION_STRING=Server=127.0.0.1;User=sa;Password=Strong!Passw0rd
      - POSTGRES_HOST=127.0.0.1
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3307
      - RABBITMQ_HOST=127.0.0.1
