version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - datadog-agent
    environment:
      OTEL_ENV: "apm-docker-samples"
      OTEL_AGENT_HOST: "datadog-agent"
      OTEL_TRACE_DEBUG: "true"
      ASPNETCORE_ENVIRONMENT: Production

  datadog-agent:
    image: "gcr.io/datadoghq/agent:7"
    environment:
      OTEL_API_KEY: ${OTEL_API_KEY}
      OTEL_APM_ENABLED: "true"
      OTEL_APM_NON_LOCAL_TRAFFIC: "true"
