version: "2"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.158.0@sha256:c5918f78992ee73b0d6f0e599423ac5ec52dd5d9726733114d6eca53d5a32ed5
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
      - ./log:/log/otel
    command: --config /etc/otel/config.yaml --feature-gates=service.profilesSupport
    environment:
      - JAEGER_ENDPOINT=jaeger:4317
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP/protobuf receiver
      - "8888:8888"   # Prometheus metrics scrape endpoint with collector telemetry
      - "8889:8889"   # Prometheus metrics exporter (scrape endpoint)
      - "9411:9411"   # Zipkin receiver
      - "13133:13133" # health_check extension
      - "55679:55679" # ZPages extension
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/jaeger:2.19.0@sha256:ede4864215be4cd85bd8c3129a2fea6c5713c5653c7282c429dba123014bc68b
    ports:
      - "16686:16686"
