version: "2"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.161.0@sha256:fd328de2552466ad78385e1b1289c3f2402b1c45f265b252aab1955b42845ac1
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
      - ./log:/log/otel
    command: --config /etc/otel/config.yaml --feature-gates=service.profilesSupport
    environment:
      - JAEGER_ENDPOINT=jaeger:4317
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP/protobuf receiver
      - "8888:8888"   # Prometheus metrics scrape endpoint with collector telemetry
      - "8889:8889"   # Prometheus metrics exporter (scrape endpoint)
      - "9411:9411"   # Zipkin receiver
      - "13133:13133" # health_check extension
      - "55679:55679" # ZPages extension
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/jaeger:2.21.0@sha256:3d0ac795ff98aa04d1be04311d2dac6c25b4bfc8322dc02e53bc5b170c5018c3
    ports:
      - "16686:16686"
