scrape_configs:
  - job_name: 'otel-collector-telemetry'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: 'otel-collector-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
