// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

namespace OpenTelemetry.AutoInstrumentation;

internal static partial class InstrumentationDefinitions
{
    internal static readonly string AssemblyFullName = typeof(InstrumentationDefinitions).Assembly.FullName!;

    internal static SharedPayload GetSharedDefinitions()
    {
        return new SharedPayload
        {
            // Fixed Id for definitions payload (to avoid loading the same integrations from multiple AppDomains).
            DefinitionsId = "57D20C392035423F9F58419EDE286903",
            Definitions = GetSharedDefinitionsArray(),
        };
    }

    internal static Payload GetAllDefinitions()
    {
        return new Payload
        {
            // Fixed Id for definitions payload (to avoid loading same integrations from multiple AppDomains)
            DefinitionsId = "FFAFA5168C4F4718B40CA8788875C2DA",

            // Autogenerated definitions array
            Definitions = GetDefinitionsArray(),
        };
    }

    internal static Payload GetDerivedDefinitions()
    {
        return new Payload
        {
            // Fixed Id for definitions payload (to avoid loading same integrations from multiple AppDomains)
            DefinitionsId = "61BF627FA9B5477F85595A9F0D68B29C",

            // Autogenerated definitions array
            Definitions = GetDerivedDefinitionsArray(),
        };
    }

    internal static Payload GetInterfaceDefinitions()
    {
        return new Payload
        {
            // Fixed Id for definitions payload (to avoid loading same integrations from multiple AppDomains)
            DefinitionsId = "6410E14A2A2343BABBB45940190E1C3F",

            // Autogenerated definitions array
            Definitions = GetInterfaceDefinitionsArray(),
        };
    }

    internal struct Payload
    {
        public string DefinitionsId { get; set; }

        public NativeCallTargetDefinition[] Definitions { get; set; }
    }

    internal struct SharedPayload
    {
        public string DefinitionsId { get; set; }

        public NativeCallTargetDefinition2[] Definitions { get; set; }
    }
}
