version: "2"
services:

  jaeger:
    image: jaegertracing/all-in-one:1.22
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"

  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"
