// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1208:SystemUsingDirectivesMustBePlacedBeforeOtherUsingDirectives", Justification = "Vendored code.")]

[assembly: SuppressMessage("StyleCop.CSharp", "SA1513", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1028", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1507", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1024", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1509", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1008", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1015", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1001", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1649", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1402", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1508", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1009", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1649", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1117", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1202", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1516", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1214", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1003", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1116", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1117", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1122", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1128", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1132", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1201", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1503", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1505", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1513", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1028", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1507", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1024", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1509", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1008", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1015", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1001", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1649", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1402", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1508", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1009", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1649", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1117", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1202", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1516", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1214", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1003", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1116", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1117", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1122", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1128", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1132", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1201", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
[assembly: SuppressMessage("StyleCop.CSharp", "SA1503", Justification = "Vendored code.", Scope = "namespaceanddescendants", Target = "DockerComposeFixture.Compose")]
