/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

// Auto-generated file, do not change it - generated by the AssemblyRedirectionSourceGenerator type

// Macro to handle cross-platform UTF-16 string literals
#ifdef _WIN32
#define _W(s) L##s
#else
#define _W(s) u##s
#endif

#define ASSEMBLY_REDIRECTION_NET \
    { 80, { \
        { _W("Microsoft.Extensions.Configuration"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Configuration.Abstractions"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Configuration.Binder"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.DependencyInjection"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.DependencyInjection.Abstractions"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Diagnostics.Abstractions"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Logging"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Logging.Abstractions"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Logging.Configuration"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Options"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Options.ConfigurationExtensions"), {8, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Primitives"), {8, 0, 0, 0} }, \
        { _W("OpenTelemetry"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Api"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Api.ProviderBuilderExtensions"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation"), {auto_major, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation.Loader"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation.StartupHook"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.Console"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.OpenTelemetryProtocol"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.Prometheus.HttpListener"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.Zipkin"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Extensions.Propagators"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Instrumentation.AspNetCore"), {1, 15, 0, 901} }, \
        { _W("OpenTelemetry.Instrumentation.EntityFrameworkCore"), {1, 15, 0, 895} }, \
        { _W("OpenTelemetry.Instrumentation.GrpcNetClient"), {1, 15, 0, 896} }, \
        { _W("OpenTelemetry.Instrumentation.Http"), {1, 15, 0, 900} }, \
        { _W("OpenTelemetry.Instrumentation.Process"), {1, 15, 0, 892} }, \
        { _W("OpenTelemetry.Instrumentation.Quartz"), {1, 15, 0, 893} }, \
        { _W("OpenTelemetry.Instrumentation.Runtime"), {1, 15, 0, 899} }, \
        { _W("OpenTelemetry.Instrumentation.SqlClient"), {1, 15, 0, 918} }, \
        { _W("OpenTelemetry.Instrumentation.StackExchangeRedis"), {1, 15, 0, 903} }, \
        { _W("OpenTelemetry.Instrumentation.Wcf"), {1, 15, 0, 890} }, \
        { _W("OpenTelemetry.Resources.Azure"), {1, 15, 0, 889} }, \
        { _W("OpenTelemetry.Resources.Container"), {1, 15, 0, 883} }, \
        { _W("OpenTelemetry.Resources.Host"), {1, 15, 0, 917} }, \
        { _W("OpenTelemetry.Resources.OperatingSystem"), {1, 15, 0, 886} }, \
        { _W("OpenTelemetry.Resources.Process"), {1, 15, 0, 887} }, \
        { _W("OpenTelemetry.Resources.ProcessRuntime"), {1, 15, 0, 885} }, \
        { _W("OpenTelemetry.Shims.OpenTracing"), {1, 0, 0, 0} }, \
        { _W("OpenTracing"), {0, 12, 1, 0} }, \
        { _W("System.Diagnostics.DiagnosticSource"), {10, 0, 0, 0} }, \
        { _W("System.Private.ServiceModel"), {4, 7, 0, 0} }, \
        { _W("System.Security.Permissions"), {4, 0, 3, 0} }, \
        { _W("System.ServiceModel"), {4, 0, 0, 0} }, \
        { _W("System.ServiceModel.Primitives"), {4, 7, 0, 0} }, \
    }}, \
    { 90, { \
        { _W("Microsoft.Extensions.Configuration"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Configuration.Abstractions"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Configuration.Binder"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.DependencyInjection"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.DependencyInjection.Abstractions"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Diagnostics.Abstractions"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Logging"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Logging.Abstractions"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Logging.Configuration"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Options"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Options.ConfigurationExtensions"), {9, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Primitives"), {9, 0, 0, 0} }, \
        { _W("OpenTelemetry"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Api"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Api.ProviderBuilderExtensions"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation"), {auto_major, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation.Loader"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation.StartupHook"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.Console"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.OpenTelemetryProtocol"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.Prometheus.HttpListener"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.Zipkin"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Extensions.Propagators"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Instrumentation.AspNetCore"), {1, 15, 0, 901} }, \
        { _W("OpenTelemetry.Instrumentation.EntityFrameworkCore"), {1, 15, 0, 895} }, \
        { _W("OpenTelemetry.Instrumentation.GrpcNetClient"), {1, 15, 0, 896} }, \
        { _W("OpenTelemetry.Instrumentation.Http"), {1, 15, 0, 900} }, \
        { _W("OpenTelemetry.Instrumentation.Process"), {1, 15, 0, 892} }, \
        { _W("OpenTelemetry.Instrumentation.Quartz"), {1, 15, 0, 893} }, \
        { _W("OpenTelemetry.Instrumentation.Runtime"), {1, 15, 0, 899} }, \
        { _W("OpenTelemetry.Instrumentation.SqlClient"), {1, 15, 0, 918} }, \
        { _W("OpenTelemetry.Instrumentation.StackExchangeRedis"), {1, 15, 0, 903} }, \
        { _W("OpenTelemetry.Instrumentation.Wcf"), {1, 15, 0, 890} }, \
        { _W("OpenTelemetry.Resources.Azure"), {1, 15, 0, 889} }, \
        { _W("OpenTelemetry.Resources.Container"), {1, 15, 0, 883} }, \
        { _W("OpenTelemetry.Resources.Host"), {1, 15, 0, 917} }, \
        { _W("OpenTelemetry.Resources.OperatingSystem"), {1, 15, 0, 886} }, \
        { _W("OpenTelemetry.Resources.Process"), {1, 15, 0, 887} }, \
        { _W("OpenTelemetry.Resources.ProcessRuntime"), {1, 15, 0, 885} }, \
        { _W("OpenTelemetry.Shims.OpenTracing"), {1, 0, 0, 0} }, \
        { _W("OpenTracing"), {0, 12, 1, 0} }, \
        { _W("System.Diagnostics.DiagnosticSource"), {10, 0, 0, 0} }, \
        { _W("System.Private.ServiceModel"), {4, 7, 0, 0} }, \
        { _W("System.Security.Permissions"), {4, 0, 3, 0} }, \
        { _W("System.ServiceModel"), {4, 0, 0, 0} }, \
        { _W("System.ServiceModel.Primitives"), {4, 7, 0, 0} }, \
    }}, \
    { 100, { \
        { _W("Microsoft.Extensions.Configuration"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Configuration.Abstractions"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Configuration.Binder"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.DependencyInjection"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.DependencyInjection.Abstractions"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Diagnostics.Abstractions"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Logging"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Logging.Abstractions"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Logging.Configuration"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Options"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Options.ConfigurationExtensions"), {10, 0, 0, 0} }, \
        { _W("Microsoft.Extensions.Primitives"), {10, 0, 0, 0} }, \
        { _W("OpenTelemetry"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Api"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Api.ProviderBuilderExtensions"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation"), {auto_major, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation.Loader"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.AutoInstrumentation.StartupHook"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.Console"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.OpenTelemetryProtocol"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.Prometheus.HttpListener"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Exporter.Zipkin"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Extensions.Propagators"), {1, 0, 0, 0} }, \
        { _W("OpenTelemetry.Instrumentation.AspNetCore"), {1, 15, 0, 901} }, \
        { _W("OpenTelemetry.Instrumentation.EntityFrameworkCore"), {1, 15, 0, 895} }, \
        { _W("OpenTelemetry.Instrumentation.GrpcNetClient"), {1, 15, 0, 896} }, \
        { _W("OpenTelemetry.Instrumentation.Http"), {1, 15, 0, 900} }, \
        { _W("OpenTelemetry.Instrumentation.Process"), {1, 15, 0, 892} }, \
        { _W("OpenTelemetry.Instrumentation.Quartz"), {1, 15, 0, 893} }, \
        { _W("OpenTelemetry.Instrumentation.Runtime"), {1, 15, 0, 899} }, \
        { _W("OpenTelemetry.Instrumentation.SqlClient"), {1, 15, 0, 918} }, \
        { _W("OpenTelemetry.Instrumentation.StackExchangeRedis"), {1, 15, 0, 903} }, \
        { _W("OpenTelemetry.Instrumentation.Wcf"), {1, 15, 0, 890} }, \
        { _W("OpenTelemetry.Resources.Azure"), {1, 15, 0, 889} }, \
        { _W("OpenTelemetry.Resources.Container"), {1, 15, 0, 883} }, \
        { _W("OpenTelemetry.Resources.Host"), {1, 15, 0, 917} }, \
        { _W("OpenTelemetry.Resources.OperatingSystem"), {1, 15, 0, 886} }, \
        { _W("OpenTelemetry.Resources.Process"), {1, 15, 0, 887} }, \
        { _W("OpenTelemetry.Resources.ProcessRuntime"), {1, 15, 0, 885} }, \
        { _W("OpenTelemetry.Shims.OpenTracing"), {1, 0, 0, 0} }, \
        { _W("OpenTracing"), {0, 12, 1, 0} }, \
        { _W("System.Private.ServiceModel"), {4, 7, 0, 0} }, \
        { _W("System.Security.Permissions"), {4, 0, 3, 0} }, \
        { _W("System.ServiceModel"), {4, 0, 0, 0} }, \
        { _W("System.ServiceModel.Primitives"), {4, 7, 0, 0} }, \
    }}
