#nullable enable
//------------------------------------------------------------------------------
// <auto-generated />
// This comment is here to prevent StyleCop from analyzing a file originally from YamlDotNet.
//------------------------------------------------------------------------------

// This file is part of YamlDotNet - A .NET library for YAML.
// Copyright (c) Antoine Aubry and contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Modified by OpenTelemetry Authors.

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using Vendors.YamlDotNet.Helpers;

namespace Vendors.YamlDotNet.Serialization.TypeInspectors
{
    public class CachedTypeInspector : TypeInspectorSkeleton
    {
        private readonly ITypeInspector innerTypeDescriptor;
        private readonly ConcurrentDictionary<Type, List<IPropertyDescriptor>> cache = new();
        private readonly ConcurrentDictionary<Type, ConcurrentDictionary<string, string>> enumNameCache = new();
        private readonly ConcurrentDictionary<object, string> enumValueCache = new();

        private readonly struct EnumNameCacheContext
        {
            public Type EnumType { get; }
            public ITypeInspector TypeInspector { get; }

            public EnumNameCacheContext(Type enumType, ITypeInspector typeInspector)
            {
                EnumType = enumType;
                TypeInspector = typeInspector;
            }
        }

        private readonly struct EnumValueCacheContext
        {
            public object EnumValue { get; }
            public ITypeInspector TypeInspector { get; }

            public EnumValueCacheContext(object enumValue, ITypeInspector typeInspector)
            {
                EnumValue = enumValue;
                TypeInspector = typeInspector;
            }
        }

        private readonly struct PropertiesCacheContext
        {
            public object? Container { get; }
            public ITypeInspector TypeInspector { get; }

            public PropertiesCacheContext(object? container, ITypeInspector typeInspector)
            {
                Container = container;
                TypeInspector = typeInspector;
            }
        }

        public CachedTypeInspector(ITypeInspector innerTypeDescriptor)
        {
            this.innerTypeDescriptor = innerTypeDescriptor ?? throw new ArgumentNullException(nameof(innerTypeDescriptor));
        }

        public override string GetEnumName(Type enumType, string name)
        {
            var cacheForType = enumNameCache.GetOrAdd(enumType, _ => new ConcurrentDictionary<string, string>());
            return cacheForType.GetOrAdd(name, static (n, context) =>
            {
                return context.TypeInspector.GetEnumName(context.EnumType, n);
            },
            new EnumNameCacheContext(enumType, innerTypeDescriptor));
        }

        public override string GetEnumValue(object enumValue)
        {
            return enumValueCache.GetOrAdd(enumValue, static (_, context) =>
            {
                return context.TypeInspector.GetEnumValue(context.EnumValue);
            },
            new EnumValueCacheContext(enumValue, innerTypeDescriptor));
        }

        public override IEnumerable<IPropertyDescriptor> GetProperties(Type type, object? container)
        {
            return cache.GetOrAdd(type, static (t, context) =>
            {
                return context.TypeInspector.GetProperties(t, context.Container).ToList();
            },
            new PropertiesCacheContext(container, innerTypeDescriptor));
        }
    }
}
