trigger:
  branches:
    include:
      - '*'
    exclude:
      - refs/pull/*/head
  paths:
    exclude:
      - docs/*
      - .github/*

variables:
  buildConfiguration: Debug
  OTEL_DOTNET_TRACER_MSBUILD:

jobs:

- job: managed
  strategy:
    matrix:
      windows:
        imageName: windows-2019
      linux:
        imageName: ubuntu-18.04
  pool:
    vmImage: $(imageName)

  steps:

  # Install the tracer latest stable release to attach the profiler to the build and test steps.
  # The script exposes the required environment variables to the following steps
  - task: PowerShell@2
    displayName: Install profiler latest release
    inputs:
      filePath: ./.azure-pipelines/setup_tracer.ps1

  - task: UseDotNet@2
    displayName: install dotnet core runtime 2.1
    inputs:
      packageType: runtime
      version: 2.1.x

  - task: UseDotNet@2
    displayName: install dotnet core runtime 3.0
    inputs:
      packageType: runtime
      version: 3.0.x

  - task: UseDotNet@2
    displayName: install dotnet core runtime 3.1
    inputs:
      packageType: runtime
      version: 3.1.x

  - task: UseDotNet@2
    displayName: install dotnet core sdk 5.0
    inputs:
      packageType: sdk
      version: 5.0.x

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      configuration: $(buildConfiguration)
      arguments: /nowarn:netsdk1138 #-l:DatadogLogger,"$(OTEL_DOTNET_TRACER_MSBUILD)"
      projects: |
        src/**/*.csproj
        test/**/*.Tests.csproj
        test/benchmarks/**/*.csproj
        !src/Datadog.Trace.Tools.Runner/*.csproj
    env:
      OTEL_SERVICE_NAME: dd-tracer-dotnet

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      configuration: $(buildConfiguration)
      projects: |
        test/**/*.Tests.csproj
    env:
      OTEL_SERVICE_NAME: dd-tracer-dotnet

- job: managed_macos
  pool:
    vmImage: macOS-10.15

  steps:

  - task: UseDotNet@2
    displayName: install dotnet core runtime 2.1
    inputs:
      packageType: runtime
      version: 2.1.x

  - task: UseDotNet@2
    displayName: install dotnet core runtime 3.0
    inputs:
      packageType: runtime
      version: 3.0.x

  - task: UseDotNet@2
    displayName: install dotnet core runtime 3.1
    inputs:
      packageType: runtime
      version: 3.1.x

  - task: UseDotNet@2
    displayName: install dotnet core sdk 5.0
    inputs:
      packageType: sdk
      version: 5.0.x

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      configuration: $(buildConfiguration)
      arguments: /nowarn:netsdk1138
      projects: |
        src/**/*.csproj
        test/**/*.Tests.csproj
        benchmarks/**/*.csproj
        !src/Datadog.Trace.Tools.Runner/*.csproj

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      configuration: $(buildConfiguration)
      projects: test/**/*.Tests.csproj


- job: windows_profiler
  strategy:
    matrix:
      x64:
        buildPlatform: x64
      x86:
        buildPlatform: x86
  pool:
    vmImage: windows-2019

  steps:

  - task: UseDotNet@2
    displayName: install dotnet core runtime 3.1
    inputs:
      packageType: runtime
      version: 3.1.x

  - task: UseDotNet@2
    displayName: install dotnet core sdk 5.0
    inputs:
      packageType: sdk
      version: 5.0.x

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      configuration: $(buildConfiguration)
      arguments: /nowarn:netsdk1138
      projects: |
        src/Datadog.Trace.ClrProfiler.Managed.Loader/Datadog.Trace.ClrProfiler.Managed.Loader.csproj
        sample-libs/**/Samples.ExampleLibrary*.csproj

  - task: NuGetToolInstaller@1
    displayName: install nuget

  - task: NuGetCommand@2
    displayName: nuget restore
    inputs:
      restoreSolution: Datadog.Trace.Native.sln
      verbosityRestore: Normal

  - task: MSBuild@1
    displayName: msbuild
    inputs:
      solution: Datadog.Trace.proj
      platform: $(buildPlatform)
      configuration: $(buildConfiguration)
      msbuildArguments: /t:BuildCpp;BuildCppTests
      maximumCpuCount: true

  - script: Datadog.Trace.ClrProfiler.Native.Tests.exe --gtest_output=xml
    displayName: run tests
    workingDirectory: $(System.DefaultWorkingDirectory)/test/Datadog.Trace.ClrProfiler.Native.Tests/bin/$(buildConfiguration)/$(buildPlatform)

  - task: PublishTestResults@2
    displayName: publish test results
    inputs:
      testResultsFiles: test/**/test*.xml
      buildPlatform: $(buildPlatform)
      buildConfiguration: $(buildConfiguration)
    condition: succeededOrFailed()

- job: linux_profiler
  pool:
    vmImage: ubuntu-20.04
  steps:

  - task: UseDotNet@2
    displayName: install dotnet core runtime 3.1
    inputs:
      packageType: runtime
      version: 3.1.x

  - task: UseDotNet@2
    displayName: install dotnet core sdk 5.0
    inputs:
      packageType: sdk
      version: 5.0.x

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      configuration: $(buildConfiguration)
      arguments: /nowarn:netsdk1138
      projects: |
        src/Datadog.Trace.ClrProfiler.Managed.Loader/Datadog.Trace.ClrProfiler.Managed.Loader.csproj
  
  - script: |
      sudo apt-get update
      sudo apt-get install -y llvm clang
    displayName: install_dependencies

  - script: |
      cd ./src/Datadog.Trace.ClrProfiler.Native
      CXX=clang++ CC=clang cmake .
      make
    displayName: build_profiler

  - script: |
      cd ./src/Datadog.Trace.ClrProfiler.Native
      CXX=clang++ CC=clang cmake .
      make
    displayName: build_profiler

- job: macos_profiler
  pool:
    vmImage: macOS-10.15
  steps:

  - task: UseDotNet@2
    displayName: install dotnet core runtime 3.1
    inputs:
      packageType: runtime
      version: 3.1.x

  - task: UseDotNet@2
    displayName: install dotnet core sdk 5.0
    inputs:
      packageType: sdk
      version: 5.0.x

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      configuration: $(buildConfiguration)
      arguments: /nowarn:netsdk1138
      projects: |
        src/Datadog.Trace.ClrProfiler.Managed.Loader/Datadog.Trace.ClrProfiler.Managed.Loader.csproj

  - script: |
      cd ./src/Datadog.Trace.ClrProfiler.Native
      cmake .
      make
    displayName: build_profiler