name: Build on Runners

on:
  workflow_call:

env:
  NUGET_PACKAGES: ${{ github.workspace }}/packages
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact-name: ubuntu-22.04
            runner: ubuntu-22.04
            environment-type: host
            replace-artifacts: |
              bin-ubuntu1604-native!linux-x64
          - artifact-name: ubuntu-22.04-arm
            runner: ubuntu-22.04-arm
            environment-type: host
          - artifact-name: macos-14
            runner: macos-14
            environment-type: host
          - artifact-name: alpine-x64
            runner: ubuntu-22.04
            environment-type: container
            dockerfile: ./docker/alpine.dockerfile
            os-type: linux-musl
          - artifact-name: alpine-arm64
            runner: ubuntu-22.04-arm
            environment-type: container
            dockerfile: ./docker/alpine.dockerfile
            os-type: linux-musl
    uses: ./.github/workflows/_build.yml
    with:
      artifact-name: ${{ matrix.artifact-name }}
      runner: ${{ matrix.runner }}
      environment-type: ${{ matrix.environment-type }}
      dockerfile: ${{ matrix.dockerfile }}
      os-type: ${{ matrix.os-type }}
      replace-artifacts: ${{ matrix.replace-artifacts }}
