name: SdkVersionCheck

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  check-sdk-versions:
    name: check-sdk-versions # Matches required status check
    runs-on: windows-2025
    steps:

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Run VerifySdkVersions
        run: ./build.cmd VerifySdkVersions
