name: SdkVersionCheck

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-sdk-versions:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag: v6.0.2

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Run VerifySdkVersions
        run: ./build.cmd VerifySdkVersions
