name: SdkVersionCheck

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  check-sdk-versions:
    name: check-sdk-versions # Matches required status check
    runs-on: windows-2025
    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Run VerifySdkVersions
        run: ./build.cmd VerifySdkVersions
