# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the tag name version
        run: echo "TRACER_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Create benchmarks branch    
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'benchmarks/${{ env.TRACER_VERSION }}'
