name: demo

on:
  push:
    branches: [ main ]
    paths:
    - examples/demo/**
  pull_request:
    branches: [ main ]
    paths:
    - examples/demo/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    name: Build demo
    strategy:
      matrix:
        os:
          # renovate: datasource=github-runners depType=github-runner
          - ubuntu-24.04
          # renovate: datasource=github-runners depType=github-runner
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Test demo
      run: make test
      working-directory: examples/demo
      timeout-minutes: 10
