name: First time contributor

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] Only code from the main branch is executed
    types: [opened]

permissions: {}

jobs:
  welcome:
    permissions:
      pull-requests: write # To post the welcome comment
    uses: open-telemetry/shared-workflows/.github/workflows/first-time-pr.yml@c717adbcb56efc45c5dea293accfc6c3462bcdd1 # v0.19.0
