name: First time contributor

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] Only code from the main branch is executed
    types: [opened]

permissions: {}

jobs:
  welcome:
    permissions:
      pull-requests: write # To post the welcome comment
    uses: open-telemetry/shared-workflows/.github/workflows/first-time-pr.yml@ee32c419ea90b05286c0cdc24538d970992cf82a # v0.11.0
