name: First time contributor

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] Only code from the main branch is executed
    types: [opened]

permissions: {}

jobs:
  welcome:
    permissions:
      pull-requests: write # To post the welcome comment
    uses: open-telemetry/shared-workflows/.github/workflows/first-time-pr.yml@6839dcd6ea227c18b59d11da34499746634728ad # v0.17.0
