name: release-publish

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  powershell-script:
    name: Run PowerShell script on ${{ matrix.machine }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - machine: windows-2022
          - machine: windows-2025
    runs-on: ${{ matrix.machine }}
    steps:

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Test the PowerShell module instructions from README.md
        shell: powershell
        env:
          GITHUB_REPOSITORY_NAME: ${{ github.repository }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          mkdir testapp
          cd testapp
          Set-Content Directory.Build.props '<Project />'
          dotnet new console
          dotnet publish -f net10.0 -c Release
          $module_url = "https://github.com/$env:GITHUB_REPOSITORY_NAME/releases/download/$env:RELEASE_TAG_NAME/OpenTelemetry.DotNet.Auto.psm1"
          $dl_path = Join-Path $env:temp "OpenTelemetry.DotNet.Auto.psm1"
          $log_path = "C:\ProgramData\OpenTelemetry .NET AutoInstrumentation\logs\*"
          Invoke-WebRequest -Uri $module_url -OutFile $dl_path
          Import-Module $dl_path
          Install-OpenTelemetryCore
          $install_dir = Get-OpenTelemetryInstallDirectory
          Register-OpenTelemetryForCurrentSession -OTelServiceName "MyServiceDisplayName"
          ./bin/Release/net10.0/publish/testapp
          if (-not $?) { throw "dotnet help returned exit code: $LASTEXITCODE" }
          if (-not (Test-Path $log_path)) { throw "Log file does not exist. Instrumentation test failed." }
          Remove-Item $log_path
          Unregister-OpenTelemetryForCurrentSession
          ./bin/Release/net10.0/publish/testapp
          if (-not $?) { throw "dotnet help returned exit code: $LASTEXITCODE" }
          if (Test-Path $log_path) { throw "Log file exists. Instrumentation unregister failed." }
          Uninstall-OpenTelemetryCore
          if (Test-Path $install_dir) { throw "Core files exist. Core uninstall failed." }

  shell-scripts:
    name: Run shell scripts on ${{ matrix.machine }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - machine: windows-2022
            log-dir: "/c/ProgramData/OpenTelemetry .NET AutoInstrumentation/logs"
          - machine: windows-2025
            log-dir: "/c/ProgramData/OpenTelemetry .NET AutoInstrumentation/logs"
          - machine: ubuntu-22.04
            log-dir: "/var/log/opentelemetry/dotnet"
          - machine: macos-14
            log-dir: "/var/log/opentelemetry/dotnet"
          - machine: ubuntu-22.04-arm
            log-dir: "/var/log/opentelemetry/dotnet"
    runs-on: ${{ matrix.machine }}
    steps:

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Install MacOS CoreUtils
        if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils

      - name: Create test directory
        if: ${{ runner.os != 'Windows' }}
        run: sudo mkdir -p "${LOG_DIRECTORY}" && sudo chmod a+rwx "${LOG_DIRECTORY}"  # the instrumented process has no permissions to create log dir
        env:
          LOG_DIRECTORY: ${{ matrix.log-dir }}

      - name: Test the Shell scripts from README.md
        shell: bash
        env:
          GITHUB_REPOSITORY_NAME: ${{ github.repository }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          LOG_DIRECTORY: ${{ matrix.log-dir }}
        run: |
          set -e
          mkdir testapp
          cd testapp
          echo "<Project />" > Directory.Build.props
          dotnet new console
          dotnet publish -f net10.0 -c Release
          curl -sSfL "https://github.com/${GITHUB_REPOSITORY_NAME}/releases/download/${RELEASE_TAG_NAME}/otel-dotnet-auto-install.sh" -O
          sh ./otel-dotnet-auto-install.sh
            test "$(ls -A "$HOME/.otel-dotnet-auto")"
          curl -sSfL "https://raw.githubusercontent.com/${GITHUB_REPOSITORY_NAME}/${GITHUB_COMMIT_SHA}/instrument.sh" -O
          . ./instrument.sh
          ./bin/Release/net10.0/publish/testapp
            test "$(ls -A "${LOG_DIRECTORY}" )"

  shell-scripts-container:
    name: Run shell scripts in Docker container on ${{ matrix.machine }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # renovate: datasource=github-runners depType=github-runner
          - machine: ubuntu-24.04
            base-image: alpine
            net-version: net10.0
          # renovate: datasource=github-runners depType=github-runner
          - machine: ubuntu-24.04-arm
            base-image: alpine
            net-version: net10.0
    runs-on: ${{ matrix.machine }}
    steps:

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Test the Shell scripts from README.md in Docker container
        env:
          BASE_IMAGE: ${{ matrix.base-image }}
          NET_VERSION: ${{ matrix.net-version }}
          GITHUB_REPOSITORY_NAME: ${{ github.repository }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
        run: |
          set -e
          docker build -t mybuildimage -f "./docker/${BASE_IMAGE}.dockerfile" .
          docker run --rm \
            -e "NET_VERSION=${NET_VERSION}" \
            -e "GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY_NAME}" \
            -e "RELEASE_TAG_NAME=${RELEASE_TAG_NAME}" \
            -e "GITHUB_COMMIT_SHA=${GITHUB_COMMIT_SHA}" \
            -i mybuildimage /bin/sh <<'EOF'
            set -e
            mkdir testapp
            cd testapp
            echo '<Project />' > Directory.Build.props
            dotnet new console
            dotnet publish -f "${NET_VERSION}" -c Release
            curl -sSfL "https://github.com/${GITHUB_REPOSITORY_NAME}/releases/download/${RELEASE_TAG_NAME}/otel-dotnet-auto-install.sh" -O
            sh ./otel-dotnet-auto-install.sh
              test "$(ls -A "$HOME/.otel-dotnet-auto")"
            curl -sSfL "https://raw.githubusercontent.com/${GITHUB_REPOSITORY_NAME}/${GITHUB_COMMIT_SHA}/instrument.sh" -O
            . ./instrument.sh
            ./bin/Release/${NET_VERSION}/publish/testapp
              test "$(ls -A /var/log/opentelemetry/dotnet )"
          EOF
