name: Shellcheck

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install shellcheck
        run: sudo apt update && sudo apt install --assume-yes shellcheck

      - name: Run shellcheck
        run: find . -name \*.sh -o -name \*.sh.template | grep -v scripts/dotnet-install.sh | xargs shellcheck --severity=warning
